### ISSUE TITLE
[2022/10/14~2022/10/21] kyo705 TODO

### ISSUE THREAD

**Issue by kyo705** [kyo705/LolSearcher#2]
- [x]  기존 비지니스 로직 리펙토링

- [x]  기존 테스트 코드 리펙토링

- [x]  시간 측정 aop 기능 추가
